# Generated by Django 4.2.7 on 2023-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Pais')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Pais')),
                ('anio_fundacion', models.DateField(verbose_name='Año de Fundación')),
                ('poblacion', models.IntegerField(verbose_name='Población')),
                ('moneda', models.CharField(max_length=50, verbose_name='Moneda')),
                ('idioma', models.CharField(max_length=50, verbose_name='Idioma')),
            ],
        ),
    ]
