# Generated by Django 4.2.7 on 2023-12-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Cultura')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Cultura')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('religion', models.CharField(max_length=50, verbose_name='Religion')),
                ('gastronomia', models.CharField(max_length=50, verbose_name='Gastronomia')),
                ('musica', models.CharField(max_length=50, verbose_name='Musica')),
            ],
        ),
        migrations.CreateModel(
            name='Gobierno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Gobierno')),
                ('tipo_gobierno', models.CharField(max_length=50, verbose_name='Tipo de Gobierno')),
                ('presidente', models.CharField(max_length=50, verbose_name='Presidente')),
                ('forma_juridica', models.CharField(max_length=50, verbose_name='Capital')),
                ('sistema_politico', models.CharField(max_length=50, verbose_name='Sistema Politico')),
                ('deuda_externa', models.CharField(max_length=50, verbose_name='Deuda Externa')),
            ],
        ),
    ]
