# Generated by Django 4.2.6 on 2024-01-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_tipocliente_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoCliente',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo_cliente',
            new_name='tipo',
        ),
    ]
